from vprdb.reduction_methods.cube_division import CubeDivision
from vprdb.reduction_methods.distance_vector import DistanceVector
from vprdb.reduction_methods.dominating_set import DominatingSet
from vprdb.reduction_methods.every_nth import EveryNth
